### ISSUE TITLE
Why is there no Star for such a useful tool!!!

### ISSUE THREAD

**Issue by mrchar** [hallidave/mibtool#1]
Recently, I am trying to develop a snmp monitoring program, I want to find a tool to read mib file to go program. Finally, I found your project mibtool. After a simple trial, I think this is a very useful tool. But why is there no star?

**Comment by hallidave** [comment]
Thanks for the star. Feel free to suggest any changes or improvements that you would also like to see.

**Comment by jihadismail8** [comment]
i would love to put a start, but i was wondering , is it possible to add an example MIB file ?  and the sample code also to have an OID from that file ? for testing
