### ISSUE TITLE
How to get description, access and other meta from mib?

### ISSUE THREAD

**Issue by wargebitebane-glich** [hallidave/mibtool#2]
Hello and THANK YOU for so nice and easy to use tool.
My question is: How can we get metadata (like DESCRIPTION, ACCESS, etc) from loaded mib modules?

**Comment by hallidave** [comment]
Not supported at the moment, unfortunately. All of the metadata is included in the parse tree (which is borrowed from libsmi), I just haven't implemented the logic to extract it.

**Comment by Hipska** [comment]
Any idea when it might be?

**Comment by hallidave** [comment]
No plan at the moment. This might work for you: https://github.com/sleepinggenius2/gosmi. Haven't tried it myself, but it looks pretty good.
